#:kivy 1.0
Widget:

	#background color, plotting window
	canvas:
		Color:
			rgba: .1, .2, .3, .8
		Rectangle:
			pos: self.pos
			size: self.size

		Rectangle:
			id: plot
			source: 'data/jeff sax.jpg'
			pos: (370, 270)
			size: (426, 420)
	Label:
		text: 'Welcome to the PyCamellia Incompressible Flow Solver!'
		pos: (133, 530)
		font_size: 13

	Label:
		text: 'Reynolds \n Number:'
		font_size: 12
		pos: (225, 451)

	Label:
		text: 'Inflow Conditions:'
		pos: (50, 367)

	Label:
		text: 'Outflow Conditions:'
		pos: (50, 192)
	Label:
		text: 'Velocity:'
		pos: (170, 367)

	Label:
		text: 'Solution Reporting Area'
		pos: (500, 200)

	Label:
		text: "Status: "
		pos: (460, 160)

	Label:
		text: 'Energy Error: '
		pos: (440, 140)

	Label:
		text: "Filename: "
		pos: (440, 55)

	#Filename entry text field
	TextInput:
		id: filename
		multiline: False
		height: '30dp'
		width: '120dp'
		pos: (527, 90)
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	#Reynolds number entry text field
	TextInput:
		id: reynolds
		multiline: False
		height: '30dp'
		width: '50dp'
		pos: (304, 485)
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	#Polynomial Order Label
	Label:
		text: "Polynomial\n         Order:"
		font_size: 12
		pos: (107, 451)

	#Polynomial Order entry Text field
	TextInput:
		id: polyOrder
		multiline: False
		height: '30dp'
		width: '50dp'
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 
		pos: (193, 485)

	#Mesh Dimensions
	Label:
		text: '            Mesh\nDimensions:'
		font_size: 12
		pos: (30,407)
	#Mesh Dimensions Label
		pos: (16,407)

	TextInput:
		id: meshDim
		multiline: False
		height: '30dp'
		width: '80dp'
		pos: (108 , 440)
		font_size: 13
		hint_text: '3.0 x 5.0'
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	#Mesh Elements
	Label:
		text: '      Mesh\nElements:'
		font_size: 12
		pos: (178,407)
	TextInput:
		multiline: False
		height: '30dp'
		width: '60dp'
		pos: (265 , 440)
		font_size: 13
		hint_text: '4 x 6'
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 


	#Reset button - should clear all fields
	Button:
		id: reset
		background_color: 
		height: 5
		width: '130dp'
		font_name: 'DroidSans'
		font_size: 15
		text: "Reset"
		pos: (220, 112)
		color: (1, 1, 1, 1)

	#Solve button - should initiate input check and solution
	Button:
		id: solve
		height: 5
		background_color: (1, .1, .1, .9)
		font_name: 'DroidSans'
		font_size: 15
		text: "Solve"
		pos: (141, 50)
		color: (1, 1, 1, 1)

	#File load button, should load solution
	Button:
		id: load
		background_color: 
		height: 5
		font_size: 15
		font_name: 'DroidSans'
		text: "Load"
		pos: (420, 50)
		color: (1, 1, 1, 1)

	#File save button, should save current solution
	Button:
		id: save
		background_color: 
		height: 5
		font_size: 15
		font_name: 'DroidSans'
		text: "Save"
		pos: (580, 50)
		color: (1, 1, 1, 1)

	#Problem Type dropdown menu
		name: 'DropDown'
		__safe_id: [dropdown.__self__]

	Button:
		id: btn
		pos: (56, 527)
		width: '250dp'
		height: '30dp'
		text: 'Problem Type »'
		on_release: dropdown.open(self)
		size_hint_y: None

	DropDown:

		id: dropdown
		on_parent: self.dismiss()
		on_select: btn.text = '{}'.format(args[1])

		Button:
			text: 'Stokes'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown.select('Stokes »')
			on_release: reynolds.disabled = True
			on_release: transient.disabled = False

		Button:
			text: 'Navier-Stokes'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown.select('Navier-Stokes »')
			on_release: reynolds.disabled = False
			on_release: transient.disabled = True
			on_release: dropdown1.select('Steady State »')

	#State selection dropdown menu
	Button:
		id: btn1
		pos: (18, 485)
		width: '100dp'
		height: '30dp'
		text: 'State »'
		on_release: dropdown1.open(self)
		size_hint_y: None

		name: 'DropDown'
		__safe_id: [dropdown1.__self__]
	
	DropDown:

		id: dropdown1
		on_parent: self.dismiss()
		on_select: btn1.text = '{}'.format(args[1])

		Button:
			id: steady
			text: 'Steady State'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown1.select('Steady State »')
		
		Button:
			id: transient
			text: 'Transient'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown1.select('Transient »')

	#Refinement selection dropdown menu
	Button:
		id: btn2
		pos: (220, 195)
		width: '130dp'
		height: '30dp'
		text: 'Refine »'
		on_release: dropdown2.open(self)
		size_hint_y: None

		name: 'DropDown'
		__safe_id: [dropdown2.__self__]

	DropDown:

		id: dropdown2
		on_parent: self.dismiss()
		on_select: btn2.text = '{}'.format(args[1])

		Button:
			text: 'h-auto'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown2.select('h-auto »')
		
		Button:
			text: 'p-auto'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown2.select('p-auto »')

	#Plotting selection dropdown menu
	Button:
		id: btn3
		pos: (220, 146)
		width: '130dp'
		height: '30dp'
		text: 'Plot »'
		on_release: dropdown3.open(self)
		size_hint_y: None

		name: 'DropDown'
		__safe_id: [dropdown3.__self__]

	DropDown:

		id: dropdown3
		on_parent: self.dismiss()
		on_select: btn3.text = '{}'.format(args[1])

		Button:
			text: 'Mesh'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('Mesh »')
		
		Button:
			text: 'Error'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('Error »')

		Button:
			text: 'u1'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('u1 »')

		Button:
			text: 'u2'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('u2 »')

		Button:
			text: 'Stream Function'
			font_size: 13
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('Stream Function »')

	#Inflow conditions
	#Inflow 1
	Label:
		text: '1. '
		pos: (20, 335)
	

	TextInput:
		multiline: False
		height: '27dp'
		width: '80dp'
		pos: (85, 375)
		font_size: 12
		hint_text: "x > 5, y = 9"
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	Label:
		text: 'x ='
		pos: (147, 338)

	TextInput:
		multiline: False
		height: '27dp'
		width: '50dp'
		pos: (210, 375)
		font_size: 11
		hint_text: "x*4"
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	Label:
		text: 'y ='
		pos: (234, 338)

	TextInput:
		multiline: False
		height: '27dp'
		width: '50dp'
		pos: (300, 375)
		font_size: 11
		hint_text: "y*4"
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 
	
	#Inflow 2
	Label:
		text: '2.'
		pos: (20, 303)
	

	TextInput:
		multiline: False
		height: '27dp'
		width: '80dp'
		pos: (85, 340)
		font_size: 12
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	Label:
		text: 'x = '
		pos: (149, 303)

	TextInput:
		multiline: False
		height: '27dp'
		width: '50dp'
		pos: (210, 340)
		font_size: 11
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	Label:
		text: 'y = '
		pos: (236, 303)

	TextInput:
		multiline: False
		height: '27dp'
		width: '50dp'
		pos: (300, 340)
		font_size: 11
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	#Inflow 3
	Label:
		text: '3.'
		pos: (20, 267)
	

	TextInput:
		multiline: False
		height: '27dp'
		width: '80dp'
		pos: (85, 305)
		font_size: 12
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 


	Label:
		text: 'x = '
		pos: (149, 267)

	TextInput:
		multiline: False
		height: '27dp'
		width: '50dp'
		pos: (210, 305)
		font_size: 11	
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	Label:
		text: 'y = '
		pos: (236, 267)

	TextInput:
		multiline: False
		height: '27dp'
		width: '50dp'
		pos: (300, 305)
		font_size: 11
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	#Inflow 4
	Label:
		text: '4.'
		pos: (20, 231)	

	TextInput:
		multiline: False
		height: '27dp'
		width: '80dp'
		pos: (85, 270)
		font_size: 12
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	Label:
		text: 'x = '
		pos: (149, 231)

	TextInput:
		multiline: False
		height: '27dp'
		width: '50dp'
		pos: (210, 270)
		font_size: 11
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	Label:
		text: 'y = '
		pos: (236, 231)

	TextInput:
		multiline: False
		height: '27dp'
		width: '50dp'
		pos: (300, 270)
		font_size: 11
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	#Outflow Conditions
	#Outflow 1
	Label:
		text: '1.'
		pos: (20, 162)

	TextInput:
		multiline: False
		height: '27dp'
		width: '80dp'
		font_size: 12
		pos: (85, 200)
		hint_text: "x = 9, y < 3"
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	
	#Outflow 2
	Label:
		text: '2. '
		pos: (20, 127)

	TextInput:
		multiline: False
		height: '27dp'
		width: '80dp'
		font_size: 12
		pos: (85, 165)
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 


	#Outflow 3
	Label:
		text: '3. '
		pos: (20, 93)

	TextInput:
		multiline: False
		height: '27dp'
		width: '80dp'
		font_size: 12
		pos: (85, 130)
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

	#Outflow 4
	Label:
		text: '4.'
		pos: (20, 58)

	TextInput:
		multiline: False
		height: '27dp'
		width: '80dp'
		font_size: 12
		pos: (85, 95)
		background_color: (1,1,1,1) #defaults to white
		#if red, reset to white:
		on_focus: polyOrder.background_color=(1,1,1,1) 

