#:kivy 1.0

Widget:
	canvas:
		Color:
			rgba: .5, .8, .8, .6
		Rectangle:
			pos: self.pos
			size: self.size

		Rectangle:
			source: 'jeff sax.jpg'
			pos: (370, 300)
			size: (450, 400)
		

	Button:
		height: 3
		background_color: (1, .1, .1, .8)
		font_name: 'DroidSans'
		font_size: 25
		text: "Solve"
		pos: (100, 50)
		color: (0, 0, 0, 1)
		on_press: print "success"


	Button:
		background_color: 
		height: 5
		font_size: 20
		text: "Load"
		pos: (400, 50)
		color: (0, 0, 0, 1)

	Button:
		background_color: 
		height: 5
		font_size: 20
		text: "Save"
		pos: (550, 50)
		color: (.6, 1, .3, .8)

		name: 'DropDown'
		__safe_id: [dropdown.__self__]

	Button:
		id: btn
		pos: (50, 400)
		text: 'Pick Something,\nNerd'
		on_release: dropdown.open(self)
		size_hint_y: None
		height: '48dp'

	Widget

	DropDown:

		id: dropdown
		on_parent: self.dismiss()
		on_select: btn.text = 'Jeff picked: {}'.format(args[1])

		Button:
			text: 'Value A'
			size_hint_y: None
			height: '48dp'
			on_release: dropdown.select('A')

		Button:
			text: 'Value B'
			size_hint_y: None
			height: '48dp'
			on_release: dropdown.select('B')

		Button:
			text: 'Value C'
			size_hint_y: None
			height: '48dp'
			on_release: dropdown.select('C')
