#:kivy 1.0
Widget:


	canvas:
		Color:
			rgba: .1, .2, .3, .8
		Rectangle:
			pos: self.pos
			size: self.size

		Rectangle:
			id: plot
			source: 'data/jeff sax.jpg'
			pos: (370, 300)
			size: (450, 400)
	Label:
		text: 'Welcome to the PyCamellia Incompressible Flow Solver!'
		pos: (133, 530)
		font_size: 13

	Label:
		text: 'Reynolds \n Number:'
		font_size: 12
		pos: (170, 430)


	Label:
		text: 'Inflow Conditions:'
		pos: (50, 370)

	Label:
		text: 'Outflow Conditions:'
		pos: (50, 250)

	Label:
		text: 'Energy Error: ... Solution Reporting Area'
		pos: (460, 225)
	

	TextInput:
		id: reynolds
		multiline: False
		height: '30dp'
		width: '50dp'
		pos: (253, 465)

	Button:
		background_color: 
		height: 5
		font_size: 20
		text: "Reset"
		pos: (660, 270)
		color: (0, 0, 0, 1)


	Button:
		height: 5
		background_color: (1, .1, .1, .9)
		font_name: 'DroidSans'
		font_size: 20
		text: "Solve"
		pos: (120, 50)
		color: (0, 0, 0, 1)
		on_press: print "success"


	Button:
		background_color: 
		height: 5
		font_size: 20
		text: "Load"
		pos: (400, 50)
		color: (0, 0, 0, 1)

	Button:
		background_color: 
		height: 5
		font_size: 20
		text: "Save"
		pos: (550, 50)
		color: (.6, 1, .3, .8)

		name: 'DropDown'
		__safe_id: [dropdown.__self__]

	Button:
		id: btn
		pos: (50, 525)
		width: '250dp'
		height: '30dp'
		text: 'Problem Type'
		on_release: dropdown.open(self)
		size_hint_y: None

	DropDown:

		id: dropdown
		on_parent: self.dismiss()
		on_select: btn.text = '{}'.format(args[1])

		Button:
			text: 'Stokes'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown.select('Stokes')
			on_release: reynolds.disabled = True
			on_release: transient.disabled = False

		Button:
			text: 'Navier-Stokes'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown.select('Navier-Stokes')
			on_release: reynolds.disabled = False
			on_release: transient.disabled = True
			on_release: dropdown1.select('Steady State')

	Button:
		id: btn1
		pos: (50, 465)
		width: '100dp'
		height: '30dp'
		text: 'State'
		on_release: dropdown1.open(self)
		size_hint_y: None

		name: 'DropDown'
		__safe_id: [dropdown1.__self__]
	
	DropDown:

		id: dropdown1
		on_parent: self.dismiss()
		on_select: btn1.text = '{}'.format(args[1])

		Button:
			id: steady
			text: 'Steady State'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown1.select('Steady State')
		
		Button:
			id: transient
			text: 'Transient'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown1.select('Transient')

	Button:
		id: btn2
		pos: (50, 105)
		width: '100dp'
		height: '30dp'
		text: 'Refine'
		on_release: dropdown2.open(self)
		size_hint_y: None

		name: 'DropDown'
		__safe_id: [dropdown2.__self__]

	DropDown:

		id: dropdown2
		on_parent: self.dismiss()
		on_select: btn2.text = '{}'.format(args[1])

		Button:
			text: 'h-auto'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown2.select('h-auto')
		
		Button:
			text: 'p-auto'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown2.select('p-auto')
	Button:
		id: btn3
		pos: (195, 105)
		width: '120dp'
		height: '30dp'
		text: 'Plot'
		on_release: dropdown3.open(self)
		size_hint_y: None

		name: 'DropDown'
		__safe_id: [dropdown3.__self__]

	DropDown:

		id: dropdown3
		on_parent: self.dismiss()
		on_select: btn3.text = '{}'.format(args[1])

		Button:
			text: 'Mesh'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('Mesh')
		
		Button:
			text: 'Error'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('Error')

		Button:
			text: 'u1'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('u1')

		Button:
			text: 'u2'
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('u2')

		Button:
			text: 'Stream Function'
			font_size: 13
			size_hint_y: None
			height: '30dp'
			on_release: dropdown3.select('Stream Function')

			